# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/qinqi/QT Designer/Save Model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveModel(object):
    def setupUi(self, SaveModel):
        SaveModel.setObjectName("SaveModel")
        SaveModel.setEnabled(True)
        SaveModel.resize(250, 200)
        SaveModel.setMinimumSize(QtCore.QSize(250, 200))
        SaveModel.setMaximumSize(QtCore.QSize(250, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(SaveModel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SaveModel)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(SaveModel)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton_1 = QtWidgets.QPushButton(SaveModel)
        self.pushButton_1.setEnabled(True)
        self.pushButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setChecked(False)
        self.pushButton_1.setAutoDefault(True)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(SaveModel)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.setStyleSheet("background-color:rgb(253, 128, 8)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(SaveModel)
        QtCore.QMetaObject.connectSlotsByName(SaveModel)

    def retranslateUi(self, SaveModel):
        _translate = QtCore.QCoreApplication.translate
        SaveModel.setWindowTitle(_translate("SaveModel", "Save Model"))
        self.label.setText(_translate("SaveModel", "Please Enter a Name (Letters Only)"))
        self.pushButton_1.setText(_translate("SaveModel", "Save"))
        self.pushButton_2.setText(_translate("SaveModel", "Cancel"))
